# Generated by Django 3.2.9 on 2022-02-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amtcmodel',
            name='sn',
            field=models.CharField(max_length=100, null=True, verbose_name='SN'),
        ),
    ]
