# Generated by Django 3.2.9 on 2022-02-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modem', '0003_auto_20220212_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amtcmodel',
            name='vlan',
            field=models.PositiveSmallIntegerField(choices=[('701', 701), ('702', 702), ('703', 703), ('704', 704), ('705', 705), ('706', 706), ('707', 707), ('708', 708), ('709', 709), ('710', 710)], default=700, null=True),
        ),
    ]
