# Generated by Django 3.2.9 on 2022-02-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modem', '0005_auto_20220212_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='amtcmodel',
            name='vaqt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
